#!/bin/bash

set -e

# Demand root.
if [[ "$UID" != 0 ]]; then
    exec sudo "$0" "$@"
fi

# Print a command, then run it.
function log_cmd {
    echo "$@"
    "$@"
}

function main {
    local script_dir=$(dirname "$0")
    log_cmd rsync -rv "$script_dir"/xkb/ /usr/share/X11/xkb/
    log_cmd cp "$script_dir"/99-keyboard-layout.conf /etc/X11/xorg.conf.d/

    # TODO: the above *almost* works on my desktop -- but currently doesn't
    # apply until I unplug and replug my keyboard. So after a reboot, it's
    # set to the standard "US" keyboard for some reason. What gives?
}

main "$@"
