#!/bin/bash

set -e

# Demand root.
if [[ "$UID" != 0 ]]; then
    exec sudo "$0" "$@"
fi

# Print a command, then run it.
function log_cmd {
    echo "$@"
    "$@"
}

function main {
    local script_dir=$(dirname "$0")
    log_cmd rsync -rv "$script_dir"/xkb/ /usr/share/X11/xkb/

    # TODO: this doesn't seem to be working on my glinux laptop.
    #log_cmd mkdir -p /etc/X11/xorg.conf.d/
    #log_cmd cp "$script_dir"/90-keyboard-wqc.conf /etc/X11/xorg.conf.d/

    #log_cmd cp "$script_dir"/90-keyboard-wqc.conf /usr/share/X11/xorg.conf.d/
}

main "$@"
