#!/bin/bash

set -e

# Print a command, then run it.
function log_cmd {
    echo "$@"
    "$@"
}

function main {
    local script_dir=$(dirname "$0")
    log_cmd setxkbmap -I "$script_dir"/xkb/ -rules wqc -layout wqc -option ctrl:nocaps,ralt_escape
}

main "$@"
