#!/bin/bash

# Install plugins.

mkdir -vp ~/.vim/bundle
pushd ~/.vim/bundle > /dev/null

git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/shougo/deoplete.nvim.git
git clone https://github.com/tpope/vim-rsi.git
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/tpope/vim-repeat.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/ctrlpvim/ctrlp.vim.git
git clone https://github.com/mileszs/ack.vim.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/koron/nyancat-vim.git
git clone https://github.com/easymotion/vim-easymotion.git
git clone https://github.com/unblevable/quick-scope.git
git clone https://github.com/justinmk/vim-sneak.git
git clone https://github.com/haya14busa/incsearch.vim.git

popd > /dev/null



# Generate plugin helptags.
# TODO: this doesn't seem to be working.
# (Is it just an issue for Nvim? Or has this never worked, even for Vim?)
# (See also the Nvim flag `-u NORC')
#vim -u NONE -c "set nocompatible" -c "execute pathogen#infect()" -c "Helptags" -c "q"
#nvim -u NONE -c "set nocompatible" -c "source ~/.vim/autoload/pathogen.vim" -c "execute pathogen#infect()" -c "Helptags" -c "q"
#nvim -u NORC -c "set nocompatible" -c "source ~/.vim/autoload/pathogen.vim" -c "execute pathogen#infect()" -c ":call pathogen#helptags()" -c "q"
