#!/bin/bash

echo rm -rf ~/.vim/bundle
rm -rf ~/.vim/bundle

plugins_dir=~/.vim/pack/plugins/start
mkdir -pv "$plugins_dir"
echo cd "$plugins_dir"
cd "$plugins_dir" || exit 1

plugins='
altercation/vim-colors-solarized
justinmk/vim-sneak
tpope/vim-sensible
tpope/vim-surround
tpope/vim-repeat
tpope/vim-rsi
tpope/vim-fugitive
tpope/vim-endwise
airblade/vim-gitgutter
haya14busa/incsearch.vim
scrooloose/nerdcommenter
scrooloose/nerdtree
mbbill/undotree
junegunn/goyo.vim
sheerun/vim-polyglot
junegunn/fzf.vim
junegunn/fzf
majutsushi/tagbar
godlygeek/tabular
dense-analysis/ale
racer-rust/vim-racer
'

for p in $plugins; do
    git clone --depth 1 https://github.com/"$p".git
done

source ~/config-files/.bash_functions || exit 1
git clone --depth 1 https://github.com/fatih/vim-go.git &&
    cd vim-go &&
    git checkout "$(get_latest_release fatih/vim-go)" 2>/dev/null
