#!/bin/bash

# Copy dotfiles to home dir.
if command -v rsync >/dev/null; then
    # If -a is given on the commandline, omit the -u flag to rsync.
    rsync $([ "$1" == -a ] && printf "" || printf "%s" "-u") -rpv \
        $(ls -d ~/config-files/.* | grep -v '/\.\.\?$') ~ \
        --exclude .git --exclude .gitignore
else
    cp -v ~/config-files/.* ~
fi

echo

# Reload bashrc definitions if you sourced this script from your shell.
echo source ~/.bashrc
source ~/.bashrc

# Reload tmux conf. Ignore failure if tmux isn't running.
echo tmux source-file ~/.tmux.conf
tmux source-file ~/.tmux.conf 2> /dev/null || :

# Generate .less file.
echo lesskey ~/config-files/lesskey
lesskey ~/config-files/lesskey
