#!/bin/bash

pushd ~/config-files > /dev/null

# Copy config files to home dir.
files=".profile .bashrc .bash_aliases .bash_functions
       .tmux.conf .vimrc .inputrc .ackrc"
for f in $files; do
    cp -v "$f" ~
done

# Reload bashrc if you sourced this script from your shell.
source ~/.bashrc

# Reload tmux conf. Ignore failure if tmux isn't running.
tmux source-file ~/.tmux.conf 2> /dev/null || :

# Install pathogen.
mkdir -vp ~/.vim/autoload
cp -v pathogen.vim ~/.vim/autoload

# Ensure swap dir exists.
mkdir -vp ~/.vim/swap

# Ensure undo dir exists.
# My work machine's Vim gives error messages when this is enabled,
# so don't do it there.
if ! [ -f ~/work/bashrc-snippet ]; then
    mkdir -vp ~/.vim/undo
fi

# Hack to disable Vim's autoindent for latex files.
mkdir -vp ~/.vim/indent
echo "let b:did_indent = 1" > ~/.vim/indent/tex.vim

popd > /dev/null
