#!/bin/bash

plugins_dir=~/.vim/pack/plugins/start
mkdir -pv "$plugins_dir"
echo cd "$plugins_dir"
cd "$plugins_dir" || exit 1

plugins='
overcache/NeoSolarized
justinmk/vim-sneak
tpope/vim-sensible
tpope/vim-surround
tpope/vim-repeat
tpope/vim-rsi
tpope/vim-fugitive
tpope/vim-endwise
airblade/vim-gitgutter
haya14busa/incsearch.vim
scrooloose/nerdcommenter
mbbill/undotree
junegunn/goyo.vim
sheerun/vim-polyglot
junegunn/fzf.vim
junegunn/fzf
majutsushi/tagbar
godlygeek/tabular
dense-analysis/ale
racer-rust/vim-racer
francoiscabrol/ranger.vim
rbgrouleff/bclose.vim
'

for p in $plugins; do
    git clone --depth 1 https://github.com/"$p".git
done
