#!/bin/bash
set -e

# Re-run this script as root.
if [[ "$UID" != 0 ]]; then
    exec sudo "$0" "$@"
fi

mkdir -p /etc/keyd
python3 generate_config.py > /etc/keyd/generic-config
cp default.conf /etc/keyd/

keyd reload
