#!/bin/bash

# Copy the layout files to the KA2's on-board drive.
#
# See the comments in 1_qwerty.txt for more info.

set -e

function main {
    local src=$(dirname "$0")
    local dest=/media/kevan/ADVANTAGE2/active

    if [[ ! -d "$dest" ]]; then
        echo Directory does not exist. Mount the drive first.
        exit 1
    fi

    cp "$src/1_qwerty.txt" "$dest/"
    cat "$src/1_qwerty.txt" "$src/2_qwerty.txt-suffix" > "$dest/2_qwerty.txt"
}

main "$@"
