#!/bin/bash

# Reset text effects
echo -en "\e[0m"

# Colors / bold / background.
# Depending on the terminal emulator, bold text may appear in brighter colors.
echo -e "\e[30mBLACK    \e[1mDARK_GRAY       \e[0;37;40m BLACK   \e[0m"
echo -e "\e[31mRED      \e[1mBRIGHT_RED      \e[0;30;41m RED     \e[0m"
echo -e "\e[32mGREEN    \e[1mBRIGHT_GREEN    \e[0;30;42m GREEN   \e[0m"
echo -e "\e[33mYELLOW   \e[1mBRIGHT_YELLOW   \e[0;30;43m YELLOW  \e[0m"
echo -e "\e[34mBLUE     \e[1mBRIGHT_BLUE     \e[0;30;44m BLUE    \e[0m"
echo -e "\e[35mMAGENTA  \e[1mBRIGHT_MAGENTA  \e[0;30;45m MAGENTA \e[0m"
echo -e "\e[36mCYAN     \e[1mBRIGHT_CYAN     \e[0;30;46m CYAN    \e[0m"
echo -e "\e[37mGRAY     \e[1mWHITE           \e[0;30;47m GRAY    \e[0m"
echo -e       "NONE     \e[1mBOLD\e[0m"
