#!/bin/bash

alias u="source ~/.config-files/update_configs"
alias co='cd ~/.config-files'

alias ls="command ls -vh --color=auto"
alias la="ls -A"
alias ll="ls -lG"
alias lla="ll -lA"
alias lt="ll -tr"
alias lta="lt -A"

alias -- -="cd -"
alias         ..="cd .."
alias        ...="cd ../.."
alias       ....="cd ../../.."
alias      .....="cd ../../../.."
alias     ......="cd ../../../../.."
alias    .......="cd ../../../../../.."
alias   ........="cd ../../../../../../.."
alias  .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."

# Misc shorthands.
alias c=cd
alias s=ls
alias e=nvim
alias er='nvim -MR'
alias se=sudoedit
alias l=less
alias a=rg
alias f='fd --hidden'
alias p=python3
alias t="time_and_notify "
alias ta=tmux_attach
alias pag="ps aux | a"
alias ltmk="latexmk -pdf -pvc --shell-escape"

# Side-by-side diff format.
alias 2jj="jj --config ui.pager='delta -s --pager less'"

alias o=cargo
alias oc="cargo_less c"
alias ob="cargo b"
alias obr="cargo b --release"
alias or="cargo r"
alias orr="cargo r -r"
alias ot="cargo t"
alias ots="cargo t -- --show-output"
alias od="cargo d"
alias odo="cargo d --open"
alias odp="cargo d --open --document-private-items"
alias of="cargo +nightly fmt"

# Misc tweaks.
alias which="type -a"
alias grep="grep --color=always"
alias tree="tree -C --gitignore"
alias vi="vi -u NONE"
alias cc="clang -Wall -Wextra -Wpedantic"
alias cx="clang++ -Wall -Wextra -Wpedantic"
alias gcc="gcc -Wall -Wextra -Wpedantic"
alias g++="g++ -Wall -Wextra -Wpedantic"

# Workaround for vscode not detecting which keyring to use.
# https://code.visualstudio.com/docs/editor/settings-sync#_recommended-configure-the-keyring-to-use-with-vs-code
alias code='code --password-store="gnome-libsecret"'
