#!/bin/bash

if command -v jj >/dev/null; then
    source <(COMPLETE=bash jj)
fi

# Use this with aliases to make completion work. For details, see:
# https://unix.stackexchange.com/questions/4219
make_completion_wrapper() {
    local comp_function_name="$1"
    local function_name="$2"
    local arg_count=$(($#-3))
    shift 2
    local function="
        function $function_name {
            ((COMP_CWORD+=$arg_count))
            # Quotes here are important
            COMP_WORDS=( "$@" \"\${COMP_WORDS[@]:1}\" )
            "$comp_function_name"
            return 0
        }"
    eval "$function"
    echo $function_name
    echo "$function"
}
