#!/bin/bash

# Time a long command and ring a bell when done.
function time_and_notify {
    # When did I start?
    date 1>&2
    echo 1>&2

    # Run and preserve the return value.
    local rv
    time "$@"
    rv=$?

    # Ring a bell, which shows up visually in tmux.
    echo -en '\a' 1>&2

    # (notify-send isn't working for me on wayland, so disable this for now)
    if [[ "$XDG_SESSION_TYPE" != wayland ]]; then
        # Trigger a "system notification", i.e. desktop pop-up.
        local command=$@  # Flatten arg array into string.
        if [[ "$rv" == 0 ]]; then
            notify-send "Command finished" "$command" -i dialog-information 2>/dev/null
        else
            notify-send "Command failed: error $rv" "$command" -i dialog-error 2>/dev/null
        fi
    fi

    return $rv
}

alias t="time_and_notify "

# Run a command, but set the terminal title to the first non-flag argument.
function title_wrapper {
    local cmd=$1
    shift
    local args=("$@")

    local title
    while [[ -n "$1" ]]; do
        # If the arg starts with anything but `-`, use it as the title.
        # This isn't perfect, but it's good enough.
        if [[ "$1" =~ ^[^-] ]]; then
            title=$1
            break
        fi

        shift
    done

    # Set the terminal title.
    if [[ -n "$title" ]]; then
        echo -ne "\e]0;$title\a"
    fi

    command "$cmd" "${args[@]}"
}

# Set the terminal title when opening man pages.
alias man="title_wrapper man"
