#!/bin/bash

# ctrl-t, ctrl-r, alt-c
source ~/.opt/fzf/shell/key-bindings.bash

# Styling.
export FZF_DEFAULT_OPTS="--height 40% --reverse --border --inline-info"

# Do show hidden files, but while respecting fd's ignores (.git, etc).
export FZF_DEFAULT_COMMAND='fd --type f --hidden'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND

# Do show hidden directories.
export FZF_ALT_C_COMMAND='
    if [[ "$PWD" == "$HOME" ]]; then
        # Ignore hidden dirs and ~/snap when used from home directory.
        fd --type d --exclude /snap
    else
        fd --type d --hidden
    fi
'

# Use alt-u for fzf cd. -- todo pick a new keybind for this.
bind -m emacs-standard '"\eu": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'



FORGIT_NO_ALIASES=true source ~/.opt/forgit/forgit.plugin.sh

# todo use side-by-side diffs when you select a file...
alias gd=forgit::diff
alias gds='forgit::diff --staged'

alias glo=forgit::log
