#!/bin/bash

# Run 'git commit', optionally accept a message for the '-m' option.
function gc {
    # Flatten arguments into a single string
    local message=$@
    local msg_len=${#message}

    if [[ "$msg_len" -eq 0 ]]; then
        command git commit
    elif [[ "$msg_len" -gt 50 ]]; then
        echo Commit message too long.
        echo Expected 50 chars, got "$msg_len".
        return 1
    else
        command git commit -m "$message"
    fi
}

# "commit all"
function gca {
    command git add --all :/ && gc "$@"
}

# "commit push"
function gcp {
    gc "$@" && command git push
}

# "commit all push"
function gcap {
    gca "$@" && command git push
}



# Switch between side-by-side and single-column delta diffs.
# Usage: `2 git diff`
alias 2='GIT_PAGER="delta -s"'

# Sadly this form breaks commandline autocompletion.
# TODO: fix it somehow. Try one of the suggestions here:
# https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases
alias g="command git"

alias gs="g s"
alias gsi="g si"
alias gp="g p"
alias gf="g f"
alias gl="g l"

#alias glo="g lo"
#alias gd="g d"
#alias gds="g ds"
#alias gc="g c"

alias gh="g h"
alias ga="g a"
alias gaa="g aa"
alias gpu="g pu"
alias gcl="g cl"
alias gco="g co"
alias gll="g ll"
alias gst="g st"
alias gsp="g sp"
alias gsl="g sl"
alias gb="g b"
alias gr="g r"
alias gcb="g cb"

alias gdni="g d --no-index"
