#!/bin/bash

# Run 'git commit', optionally accept a message for the '-m' option.
function gc {
    # Flatten arguments into a single string
    local message=$@
    local msg_len=${#message}

    if [[ "$msg_len" -eq 0 ]]; then
        git commit
    elif [[ "$msg_len" -gt 50 ]]; then
        echo Commit message too long.
        echo Expected 50 chars, got "$msg_len".
        return 1
    else
        git commit -m "$message"
    fi
}

# "commit all"
function gca {
    git add --all :/ && gc "$@"
}

# "commit push"
function gcp {
    gc "$@" && git push
}

# "commit all push"
function gcap {
    gca "$@" && git push
}

# Switch between side-by-side and single-column delta diffs.
# Usage: `2 git diff`
alias 2='GIT_PAGER="delta -s"'

# Note that this breaks bash completion, and I haven't been able to get the
# following to work for me:
# https://stackoverflow.com/questions/9869227
alias g="git"

alias gs="g s"
alias gd="g d"
alias gds="g ds"
alias gp="g p"
alias gpu="g pu"
alias gl="g l"
alias gll="g ll"

alias gdni="g d --no-index"
