#!/bin/bash

alias get="jj git clone --depth 1"

alias n="jj"
alias ns="jj st"
alias ne="jj new"
alias np="jj prev"
alias nn="jj next"
alias nf='jj git fetch'

# Side-by-side diff format.
alias 2n="jj --config ui.pager='delta -s --pager less'"

# 'jj desc', but optionally accepts a message for the '-m' option.
function nd {
    # Flatten arguments into a single string.
    local message=$@
    local msg_len=${#message}

    if [[ "$msg_len" -eq 0 ]]; then
        command jj desc
    else
        command jj desc -m "$message"
    fi
}

# 'jj desc' and push.
function ndp {
    nd "$@" && jj b s main -r@ && jj git push
}

# 'jj desc' and 'jj new'
function nde {
    nd "$@" && jj new
}
