#!/bin/bash

# Unmap C-s from freezing tty output, so that it can be used for i-search.
stty -ixon

# Filter duplicates out of history.
export HISTCONTROL=ignoredups

# Keep a much larger history file (default is 500 lines).
export HISTSIZE=100000

# Don't leave .pyc files or __pycache__ dirs lying around.
export PYTHONDONTWRITEBYTECODE=1

# Tell ripgrep where to find configs.
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/config
