#!/bin/bash

PROMPT_COMMAND=prompt_command

#prompt_contents='\u@\h:\w'
prompt_contents='\w'

# Different prompt colors on different machines, to tell them apart.
regex='^kevan-.*$|^khollbach-.*$|^mug.*$|^bumblebee.*$'
if [[ $(hostname) =~ $regex ]]; then
    # Local machine: red.
    prompt_color=9
else
    # Remote machine: cyan.
    prompt_color=14
fi
unset regex

# This sets the prompt, $PS1.
#
# It automatically re-runs each time, just before the prompt is printed.
function prompt_command {
    # Reset the terminal title after running any program, since it seems many
    # programs set it and then forget to clean it up when they exit.
    echo -ne "\e]0;\a"

    # Color escape codes.
    local color='\[\e[1;38;5;'"$prompt_color"'m\]'  # bold text, colorful
    local reset='\[\e[0m\]'

    # Add a line break if $prompt_contents is anything more than '\w', or \w is
    # longer than 48 chars.
    local newline=""
    local w=$(dirs +0)
    if [[ -n "$prompt_contents" && ("$prompt_contents" != '\w' || ${#w} -gt 48) ]]; then
        newline="\n"
    fi

    # Set the prompt; e.g.:
    # |
    # | user@hostname:~/some-dir
    # | $ _
    # or:
    # |
    # | ~/some-dir$ _
    PS1="$reset\n"
    PS1="$PS1$color$prompt_contents$reset$newline"
    PS1="$PS1$color"'\$'"$reset "
}
