#!/bin/bash

# See https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
# Vim has its own names for these colors, see :help cterm-colors

echo -e "\e[00;30mCOLOR_BLACK      \e[01;30mCOLOR_DARK_GRAY"
echo -e "\e[00;31mCOLOR_RED        \e[01;31mCOLOR_LIGHT_RED"
echo -e "\e[00;32mCOLOR_GREEN      \e[01;32mCOLOR_LIGHT_GREEN"
echo -e "\e[00;33mCOLOR_YELLOW     \e[01;33mCOLOR_LIGHT_YELLOW"
echo -e "\e[00;34mCOLOR_BLUE       \e[01;34mCOLOR_LIGHT_BLUE"
echo -e "\e[00;35mCOLOR_MAGENTA    \e[01;35mCOLOR_LIGHT_MAGENTA"
echo -e "\e[00;36mCOLOR_CYAN       \e[01;36mCOLOR_LIGHT_CYAN"
echo -e "\e[00;37mCOLOR_GRAY       \e[01;37mCOLOR_WHITE"
echo -e "\e[mCOLOR_NC (No color)"
