#!/bin/bash

# When on my laptop,
if [[ "$HOSTNAME" == kevan-thinkpad
    || "$HOSTNAME" == kevan-ThinkPad-T450s ]]; then

    # run zoomed-in version of firefox, for high-dpi screens.
    GDK_DPI_SCALE=1.5 /usr/bin/firefox "$@"
else
    /usr/bin/firefox "$@"
fi
