#!/bin/bash

# If run from $HOME, run the given shell command in each direct subdirectory
# of $HOME that is a git repository.
#
# Otherwise, simply run the given shell command in $PWD.
#
# This script is called `gitrecurse' for historical reasons, it doesn't recurse
# into subsubdirs anymore for performance reasons.
#
# Sample usage: `gitrecurse git status -s`
# Sample usage: `gitrecurse git pull`
main() {
    local shell_command
    shell_command=("$@")

    if [[ "$PWD" == "$HOME" ]]; then
        for dir in */; do
            pushd "$dir" > /dev/null || continue

            # If this is the root of a git repo, print the repo name (in blue)
            # and then run the command.
            if [[ -d .git && ! -L .git ]]; then
                echo -e "\e[0;34m$PWD\e[0m"
                "${shell_command[@]}"
            fi

            popd > /dev/null || exit 1
        done
    else
        "${shell_command[@]}"
    fi
}

main "$@"
