#!/bin/bash

# Start tmux. If a session is already running that isn't attached to, then
# attach to that session instead of starting a new one.

# Force 256 colors.
export TERM=screen-256color

# Force UTF-8.
tmux() {
    command tmux -u "$@"
}

sessions=$(tmux ls 2> /dev/null)
retval=$?

# If tmux ls fails (ie no tmux server running), start a new session.
if [[ $retval != 0 ]]; then
    tmux
    exit $?
fi

unattached_sessions=$(echo "$sessions" | grep -v attached)

# If there are no unattached sessions, start a new one.
# Otherwise, attach to an existing one.
if [[ "$unattached_sessions" == "" ]]; then
    tmux
else
    session=$(echo "$unattached_sessions" | head -n 1 | cut -d ":" -f 1)
    tmux attach -t "$session"
fi
