#!/bin/bash

# If not inside a tmux session, re-run from inside one, but hide the status
# bar.
if [[ -z "$TMUX" ]]; then
    exec tmux new-session "$0" "$@" \; set-option status off
fi

# Start nvim.
exec nvim "$@"
