#!/bin/bash

# Start tmux. If a session is already running that isn't attached to, then
# attach to that session instead of starting a new one.
main() {
    # If tmux isn't running at all, or if all sessions are already attached to,
    # this will be empty.
    local unattached_sessions=$(tmux ls 2> /dev/null | grep -v attached)

    if [[ "$unattached_sessions" == "" ]]; then
        # Start a new session.
        exec tmux
    fi

    # Attach to an existing session.
    local session=$(echo "$unattached_sessions" | head -n 1 | cut -d ":" -f 1)
    exec tmux attach-session -t "$session"
}

main "$@"
