#!/bin/bash

# If not inside a tmux session, re-run from inside one.
if [[ -z "$TMUX" ]]; then
    exec tmux new-session "$0" "$@"
fi

# Start Nvim.
tmux set-option status off
exec nvim -c 'set wrap cc= fcs=eob:\ ' "$@"
