#!/bin/bash

# Toggle colors between light and dark. Done via hardcoded sed commands, so
# it's pretty brittle.

cfg=~/config-files

isDark() {
    grep -q -E '^\s*set background=dark$' "$cfg/.vimrc"
}

darkToLight() {
    # Vim
    sed -i -E 's,^(\s*set background=)dark$,\1light,g;
               s,^(autocmd VimEnter \* set laststatus)=2$,\1=1,g' \
        "$cfg/.vimrc"

    # tmux
    # Uncomment "set ... fg" lines.
    sed -i -E 's,^(\s*)#(set .* fg=.*)$,\1\2,g' "$cfg/.tmux.conf"

    # diff-so-fancy
    # Uncomment "(new|old)Highlight" lines.
    sed -i -E 's,^(\s*)#((old|new)Highlight = .*)$,\1\2,g' "$cfg/.config/git/config"
}

lightToDark() {
    # Vim
    sed -i -E 's,^(\s*set background=)light$,\1dark,g;
               s,^(autocmd VimEnter \* set laststatus)=1$,\1=2,g' \
        "$cfg/.vimrc"

    # tmux (using Perl instead of sed, as per https://unix.stackexchange.com/questions/26284/how-can-i-use-sed-to-replace-a-multi-line-string)
    # Comment out three specific lines.
    local pattern='(\s*)(set -g \S+ fg=\S+)\n'
    perl -0 -pi -e 's/(# Light grey[^\n]*)\n'"$pattern$pattern$pattern"'/\1\n\2#\3\n\4#\5\n\6#\7\n/gm' "$cfg/.tmux.conf"

    # diff-so-fancy
    # Comment out "(new|old)Highlight" lines corresponding to light theme.
    sed -i -E 's,^(\s*)((old|new)Highlight = .* (224|194) .*)$,\1#\2,g' "$cfg/.config/git/config"
}

if isDark; then
    darkToLight
else
    lightToDark
fi

"$cfg/update_configs"
