#!/bin/bash

# Toggle colors between light and dark. Done via hardcoded sed commands, so
# it's pretty brittle.

cfg=~/config-files

isDark() {
    grep -q -E '^\s*set background=dark$' "$cfg/.vimrc"
}

toLight() {
    # Vim
    sed -i -E 's,^(\s*set background=)dark$,\1light,g' "$cfg/.vimrc"

    # tmux
    # Uncomment "set ... fg" lines.
    sed -i -E 's,^(\s*)#(set .* fg=.*)$,\1\2,g' "$cfg/.tmux.conf"

    # diff-so-fancy
    # Uncomment "(new|old)Highlight" lines.
    sed -i -E 's,^(\s*)#((old|new)Highlight = .*)$,\1\2,g' "$cfg/.config/git/config"

    # FZF
    sed -i -E 's,^(export FZF_DEFAULT_OPTS="--color) (dark)"$,\1 light",g' "$cfg/.bashrc"

    # xfce4-terminal
    # This palette is tweaked slightly from the original to make color 11 the
    # same as color 10.
    local solarized_tweaked='#073642;#dc322f;#859900;#b58900;#268bd2;#d33682;#2aa198;#eee8d5;#002b36;#cb4b16;#586e75;#586e75;#839496;#6c71c4;#93a1a1;#fdf6e3'
    sed -i -E 's,^(ColorForeground)=.*$,\1=#073642,g;
               s,^(ColorBackground)=.*$,\1=#fdf6e3,g;
               s,^(ColorCursor)=.*$,\1=#073642,g;
               s,^(ColorBold)=.*$,\1=#073642,g;'"
               s/^(ColorPalette)=.*$/\\1=$solarized_tweaked/g" \
        ~/.config/xfce4/terminal/terminalrc
}

toDark() {
    # Vim
    sed -i -E 's,^(\s*set background=)light$,\1dark,g' "$cfg/.vimrc"

    # tmux (using Perl instead of sed, as per https://unix.stackexchange.com/questions/26284/how-can-i-use-sed-to-replace-a-multi-line-string)
    # Comment out three specific lines.
    local pattern='(\s*)(set -g \S+ fg=\S+)\n'
    perl -0 -pi -e 's/(# Light grey[^\n]*)\n'"$pattern$pattern$pattern"'/\1\n\2#\3\n\4#\5\n\6#\7\n/gm' "$cfg/.tmux.conf"

    # diff-so-fancy
    # Comment out "(new|old)Highlight" lines corresponding to light theme.
    sed -i -E 's,^(\s*)((old|new)Highlight = .* (224|194) .*)$,\1#\2,g' "$cfg/.config/git/config"

    # FZF
    sed -i -E 's,^(export FZF_DEFAULT_OPTS="--color) (light)"$,\1 dark",g' "$cfg/.bashrc"

    # xfce4-terminal
    local solarized='#073642;#dc322f;#859900;#b58900;#268bd2;#d33682;#2aa198;#eee8d5;#002b36;#cb4b16;#586e75;#657b83;#839496;#6c71c4;#93a1a1;#fdf6e3'
    sed -i -E 's,^(ColorForeground)=.*$,\1=#839496,g;
               s,^(ColorBackground)=.*$,\1=#002b36,g;
               s,^(ColorCursor)=.*$,\1=#93a1a1,g;
               s,^(ColorBold)=.*$,\1=#93a1a1,g;'"
               s/^(ColorPalette)=.*$/\\1=$solarized/g" \
        ~/.config/xfce4/terminal/terminalrc
}

if isDark; then
    toLight
else
    toDark
fi

"$cfg/update_configs"
